version: '3.8'

services:
  api:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./samples.yaml:/app/samples.yaml
    environment:
      - SAMPLES_PATH=/app/samples.yaml
      - NEO4J_URI=bolt://192.168.0.117:7687
      - NEO4J_USER=puppygraph
      - NEO4J_PASSWORD=puppyheap3
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
