services:
  puppygraph:
    image: puppygraph/puppygraph:0.52
    container_name: puppygraph
    environment:
      - PUPPYGRAPH_USERNAME=puppygraph
      - PUPPYGRAPH_PASSWORD=puppyheap3
      - GRAPH_FEATURES=feature.engine.enableCypherEngine:true
    networks:
      postgres_net:
    ports:
      - "8081:8081"
      - "7687:7687"
  postgres:
    image: postgres:14.1-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    networks:
      postgres_net:
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./csv_data:/tmp/csv_data
      - ./postgres-schema.sql:/docker-entrypoint-initdb.d/postgres-schema.sql
networks:
  postgres_net:
    name: puppy-postgres
